const ContactActionType = {
    CONTACT_ADD:"CONTACT_ADD",
    CONTACT_GET_ALL:"CONTACT_GET_ALL",
    CONTACT_GET_BY_ID:"CONTACT_GET_BY_ID",
    CONTACT_UPDATE:"CONTACT_UPDATE",
    CONTACT_DELETE:"CONTACT_DELETE"
}

export default ContactActionType;